FROM node:20-alpine

WORKDIR /app

# Development: dependencies will be installed via volume mount
EXPOSE 3000

ENV PORT 3000
ENV WATCHPACK_POLLING true

CMD ["sh", "-c", "npm install && npm run dev"]
