[supervisord]
user=www-data
nodaemon=true
logfile=/var/www/backend/storage/logs/supervisord.log
pidfile=/var/run/supervisord.pid

[program:octane]
command=php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=auto --max-requests=500
autostart=true
autorestart=true
user=www-data
stdout_logfile=/var/www/backend/storage/logs/octane.log
stderr_logfile=/var/www/backend/storage/logs/octane.error.log

[program:horizon]
command=php artisan horizon
autostart=true
autorestart=true
user=www-data
stdout_logfile=/var/www/backend/storage/logs/horizon.log
stderr_logfile=/var/www/backend/storage/logs/horizon.error.log
